"""Claude CLI execution for research tasks using research-retrieval skill."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_TIMEOUT_SECONDS = 30 * 60  # 30 minutes


def run_research(
    url: str,
    output_dir: Path,
    work_dir: str | Path,
    claude_options: str = "",
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> list[Path]:
    """Execute Claude CLI with research-retrieval skill and return generated report files.

    Args:
        url: URL of the resource to investigate.
        output_dir: Directory where reports will be written by the skill.
        work_dir: Repository root directory.
        claude_options: Additional Claude CLI options.
        timeout: Timeout in seconds.

    Returns:
        List of generated report file paths.
    """
    work_dir = Path(work_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    existing_files = set(output_dir.glob("*.md"))

    prompt = f"/research-retrieval --auto {url}"
    logger.info("Running Claude CLI with research-retrieval skill (timeout: %ds)", timeout)
    logger.info("URL: %s, output_dir: %s", url, output_dir)

    cmd = [
        "claude",
        "-p",
        prompt,
        "--allowedTools",
        "WebSearch",
        "WebFetch",
        "Read",
        "Write",
        "Edit",
        "Glob",
        "Grep",
    ]
    if claude_options:
        cmd.extend(claude_options.split())

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(output_dir),
        timeout=timeout,
    )

    if result.returncode != 0:
        logger.error("Claude CLI failed (exit code %d): %s", result.returncode, result.stderr)
        raise RuntimeError(f"Claude CLI failed with exit code {result.returncode}: {result.stderr}")

    new_files = sorted(set(output_dir.glob("*.md")) - existing_files)

    if not new_files:
        logger.warning("No new files generated by skill, falling back to stdout capture")
        output = result.stdout
        heading_pos = output.find("\n# ")
        if heading_pos != -1 and not output.lstrip().startswith("#"):
            output = output[heading_pos + 1 :]
        if output and len(output.strip()) >= 10:
            fallback_path = output_dir / "report.md"
            fallback_path.write_text(output, encoding="utf-8")
            new_files = [fallback_path]
            logger.info("Saved stdout fallback to %s (%d chars)", fallback_path, len(output))
        else:
            raise RuntimeError("Claude CLI produced no output files and empty stdout")

    for f in new_files:
        logger.info("Generated report: %s (%d bytes)", f.name, f.stat().st_size)

    return new_files
